version: 2

run:
  # Note: This is set to 1.22 for golangci-lint compatibility
  # The actual project uses Go 1.24.3 (see go.mod)
  # This is a temporary workaround until golangci-lint supports Go 1.24
  go: "1.22"
  timeout: 5m
  tests: true
  build-tags:
    - all
  modules-download-mode: readonly

linters:
  disable:
    - typecheck  # Disabled due to Go 1.24.3 compatibility issue
  enable:
    - govet
    - ineffassign
    - misspell
    - unconvert
    - prealloc
    - nakedret
    - gocyclo
    - dupl
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100

issues:
  max-issues-per-linter: 100
  max-same-issues: 10
  exclude-dirs:
    - vendor
    - .git
    - .terraform
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - errcheck
    - path: examples/
      linters:
        - errcheck
        - gosec
    - text: "G101|G404|G304"  # Allow some security issues temporarily
      linters:
        - gosec