// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/aashari/go-generative-api-router",
            "email": "support@yourcompany.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns structured health information including status, services, and version details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "Structured health response",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.HealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/chat/completions": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Routes chat completion requests to different language model providers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Chat completions API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Optional vendor to target (e.g., 'openai', 'gemini')",
                        "name": "vendor",
                        "in": "query"
                    },
                    {
                        "description": "Chat completion request in OpenAI-compatible format",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.ChatCompletionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OpenAI-compatible chat completion response",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.ChatCompletionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/models": {
            "get": {
                "description": "Returns a list of available language models in OpenAI-compatible format",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "List available models",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Optional vendor to filter models (e.g., 'openai', 'gemini')",
                        "name": "vendor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of available models",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.ModelsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_handlers.ChatCompletionRequest": {
            "type": "object"
        },
        "internal_handlers.ChatCompletionResponse": {
            "type": "object",
            "properties": {
                "choices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handlers.Choice"
                    }
                },
                "created": {
                    "type": "integer",
                    "example": 1677652288
                },
                "id": {
                    "type": "string",
                    "example": "chatcmpl-abc123"
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4o"
                },
                "object": {
                    "type": "string",
                    "example": "chat.completion"
                },
                "service_tier": {
                    "type": "string",
                    "example": "default"
                },
                "system_fingerprint": {
                    "type": "string",
                    "example": "fp_abc123"
                },
                "usage": {
                    "$ref": "#/definitions/internal_handlers.Usage"
                }
            }
        },
        "internal_handlers.Choice": {
            "type": "object",
            "properties": {
                "finish_reason": {
                    "type": "string",
                    "example": "stop"
                },
                "index": {
                    "type": "integer",
                    "example": 0
                },
                "logprobs": {
                    "type": "string",
                    "example": "null"
                },
                "message": {
                    "$ref": "#/definitions/internal_handlers.Message"
                }
            }
        },
        "internal_handlers.ErrorInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "invalid_model"
                },
                "message": {
                    "type": "string",
                    "example": "Invalid model specified"
                },
                "param": {
                    "type": "string",
                    "example": "model"
                },
                "type": {
                    "type": "string",
                    "example": "invalid_request_error"
                }
            }
        },
        "internal_handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/internal_handlers.ErrorInfo"
                }
            }
        },
        "internal_handlers.HealthResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "services": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "Hello, how are you?"
                },
                "name": {
                    "type": "string",
                    "example": "John"
                },
                "role": {
                    "type": "string",
                    "example": "user"
                },
                "tool_call_id": {
                    "type": "string"
                },
                "tool_calls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handlers.ToolCall"
                    }
                }
            }
        },
        "internal_handlers.Model": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "integer",
                    "example": 1677610602
                },
                "id": {
                    "type": "string",
                    "example": "gpt-4o"
                },
                "object": {
                    "type": "string",
                    "example": "model"
                },
                "owned_by": {
                    "type": "string",
                    "example": "openai"
                }
            }
        },
        "internal_handlers.ModelsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handlers.Model"
                    }
                },
                "object": {
                    "type": "string",
                    "example": "list"
                }
            }
        },
        "internal_handlers.TokenDetails": {
            "type": "object",
            "properties": {
                "accepted_prediction_tokens": {
                    "type": "integer",
                    "example": 0
                },
                "audio_tokens": {
                    "type": "integer",
                    "example": 0
                },
                "cached_tokens": {
                    "type": "integer",
                    "example": 0
                },
                "reasoning_tokens": {
                    "type": "integer",
                    "example": 0
                },
                "rejected_prediction_tokens": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "internal_handlers.ToolCall": {
            "type": "object",
            "properties": {
                "function": {
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "type": "string",
                    "example": "call_8qty38"
                },
                "type": {
                    "type": "string",
                    "example": "function"
                }
            }
        },
        "internal_handlers.Usage": {
            "type": "object",
            "properties": {
                "completion_tokens": {
                    "type": "integer",
                    "example": 20
                },
                "completion_tokens_details": {
                    "$ref": "#/definitions/internal_handlers.TokenDetails"
                },
                "prompt_tokens": {
                    "type": "integer",
                    "example": 10
                },
                "prompt_tokens_details": {
                    "description": "Added additional usage details for OpenAI compatibility",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_handlers.TokenDetails"
                        }
                    ]
                },
                "total_tokens": {
                    "type": "integer",
                    "example": 30
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and the API key value.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "genapi.aduh.xyz",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Generative API Router",
	Description:      "A router for generative AI models with OpenAI-compatible API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
